### ISSUE TITLE
More robust theme API

### ISSUE THREAD

**Issue by emmettu** [emmettu/weefig#3]
Hi figteam,

Currently themes can be defined as a repeating sequence.

The next logical change is to incorporate a grid based theme system, and possibly let users specify files where they keep their themes. 

Please do not begin work on this issue until the implementation of the new theme system has been established.

Thank you,

Emmett Underhill

**Comment by Ian-Stewart-Binks** [comment]
@emmettu I understand, and I agree that this is the next logical step. Good work.

> Please do not begin work on this issue until the implementation of the new theme system has been established.

Can you please clarify what the new theme system is? This is the first time I'm hearing about this task.

I'll organize the figteam to get on this right away.

Sincerely,
Ian

**Comment by emmettu** [comment]
> Can you please clarify what the new theme system is? This is the first time I'm hearing about this task.

I think the team should decide on what the implementation for the new theme API should look like.

Thank you,

Emmett Underhill

**Comment by Ian-Stewart-Binks** [comment]
> I think the team should decide on what the implementation for the new theme API should look like.

As in, if the user wants a checkerboard theme vs. stripes sort of deal?

Sincerely,
Ian

**Comment by emmettu** [comment]
> As in, if the user wants a checkerboard theme vs. stripes sort of deal?

Yes, and I think that the way to implement this is to change theme definitions to matrices (lists of lists instead of just one list), and color character by character instead of line by line.

I am currently looking into this, but am open to other suggestions.

Thank you,

Emmett Underhill

**Comment by emmettu** [comment]
The new robust theme API has been implemented and merged with master.
